FoodDeliveryMvcApp/Models/ErrorViewModel.cs
using System;

namespace FoodDeliveryMvcApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FoodDeliveryMvcApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodDeliveryMvcApp.BusinessLayer.Interface;
using FoodDeliveryMvcApp.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryMvcApp.Controllers
{
    public class AdminController : Controller
    {
        private readonly IRestorentService _service;
        public AdminController(IRestorentService service)
        {
            _service = service;
        }
        // GET: Admin
        public ActionResult GetRestorentDetails()
        {

            return View();
        }
        public ActionResult AddRestorents()
        {

            return View();
        }
        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddRestorents(Restorents restorent)
        {
            try
            {
                var restornets = await _service.RestorentCreateAsync(restorent);
            
                return RedirectToAction("GetRestorentDetails", "Admin");
            }
            catch
            {
                return View();
            }
        }

    }
}

FoodDeliveryMvcApp/Controllers/FoodItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodDeliveryMvcApp.BusinessLayer.Interface;
using FoodDeliveryMvcApp.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryMvcApp.Controllers
{
    public class FoodItemController : Controller
    {
        private readonly IRestorentService _service;
        public FoodItemController(IRestorentService service)
        {
            _service = service;
        }
        // GET: FoodItem
        public ActionResult OrderFood()
        {
            return View();
        }
        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> OrderFood(FoodIteam fooditem)
        {
            try
            {
                await _service.FooditemCreateAsync(fooditem);
                return RedirectToAction("GetRestorentDetails", "Admin");
            }
            catch
            {
                return View();
            }
        }

    }
}

FoodDeliveryMvcApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FoodDeliveryMvcApp.Models;

namespace FoodDeliveryMvcApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FoodDeliveryMvcApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FoodDeliveryMvcApp.BusinessLayer.Interface;
using FoodDeliveryMvcApp.Entities;

namespace FoodDeliveryMvcApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _service;
        public UserController(IUserService service)
        {
            _service = service;
        }

        /// <summary>
        /// return to view user login form
        /// </summary>
        /// <returns></returns>
        // GET: User
        public ActionResult Login()
        {
            return View();
        }
        /// <summary>
        /// return to View user signup form
        /// </summary>
        /// <returns></returns>

        // GET: User/SignUp
        public ActionResult SignUp()
        {
            return View();
        }

        /// <summary>
        /// Send User login details to service\
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: User/LoginUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoginUser(Login login)
        {
            try
            {
                await _service.UserloginReadAsync(login);

                return RedirectToAction("GetRestorentDetails", "Admin");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Send Userregister details to service
        /// </summary>
        /// <param name="signup"></param>
        /// <returns></returns>

        // POST: User/RegisterUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SignUp(SignUp signup)
        {
            try
            {
                // TODO: Add insert logic here
                await _service.UserSignUpCreateAsync(signup);

                return RedirectToAction("Login", "User");
            }
            catch
            {
                return View();
            }
        }
    }
}

FoodDeliveryMvcApp/Views/Admin/AddRestorents.cshtml
@model FoodDeliveryMvcApp.Entities.Restorents

@{
    ViewData["Title"] = "AddRestorents";
}

<h1>AddRestorents</h1>

<h4>Restorents</h4>
<hr />
@using (Html.BeginForm("AddRestorents", "Admin", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="AddRestorents">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="RestorentName" class="control-label"></label>
                    <input asp-for="RestorentName" class="form-control" />
                    <span asp-validation-for="RestorentName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="address" class="control-label"></label>
                    <input asp-for="address" class="form-control" />
                    <span asp-validation-for="address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="reviews" class="control-label"></label>
                    <input asp-for="reviews" class="form-control" />
                    <span asp-validation-for="reviews" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}

FoodDeliveryMvcApp/Views/Admin/GetRestorentDetails.cshtml
@model IEnumerable<FoodDeliveryMvcApp.Entities.Restorents>

@{
    ViewData["Title"] = "Admin";
}
<div class="text-center">
    <h1 class="display-4">Please order food in Your Favorite Restorent</h1>
</div>
<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AddRestorents">AddRestorents</a>
        </li>
    </ul>
</div>
<table class="table">
    <tr>
        <th>RestorentName</th>
        <th>Address</th>
        <th>review</th>
        <th>OrderFood</th>
    </tr>
    @foreach (var list in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelitem => list.RestorentName)
            </td>
            <td>
                @Html.DisplayFor(modelitem => list.address)
            </td>
            <td>
                @Html.DisplayFor(modelitem => list.reviews)
            </td>
            <td>
                <a asp-area="" asp-controller="FoodItem" asp-action="OrderFood">OrderFood</a>
            </td>
        </tr>
    }
</table>

FoodDeliveryMvcApp/Views/FoodItem/OrderFood.cshtml
@model FoodDeliveryMvcApp.Entities.FoodIteam

@{
    ViewData["Title"] = "OrderFood";
}

<h1>OrderFood</h1>

<h4>FoodIteam</h4>
<hr />
@using (Html.BeginForm("OrderFood", "FoodItem", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="OrderFood">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FoodItem" class="control-label"></label>
                    <input asp-for="FoodItem" class="form-control" />
                    <span asp-validation-for="FoodItem" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cost" class="control-label"></label>
                    <input asp-for="Cost" class="form-control" />
                    <span asp-validation-for="Cost" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RestorentName" class="control-label"></label>
                    <input asp-for="RestorentName" class="form-control" />
                    <span asp-validation-for="RestorentName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="PlaceOrder" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
 

FoodDeliveryMvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To FoodDeliveryApp</h1>
</div>
<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Add Restorents</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignUp">View Restorents</a>
        </li>
    </ul>
</div>

FoodDeliveryMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodDeliveryMvcApp</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodDeliveryMvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignUp">Create Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

FoodDeliveryMvcApp/Views/User/Login.cshtml
@model FoodDeliveryMvcApp.Entities.Login

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<h4>Login</h4>
<hr />
@using (Html.BeginForm("LoginUser", "User", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Login">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}


    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FoodDeliveryMvcApp/Views/User/SignUp.cshtml
@model FoodDeliveryMvcApp.Entities.SignUp

@{
    ViewData["Title"] = "SignUp";
}

<h1>SignUp</h1>

<h4>SignUp</h4>
<hr />
@using (Html.BeginForm("SignUp", "User", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="SignUp">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EmailId" class="control-label"></label>
                    <input asp-for="EmailId" class="form-control" />
                    <span asp-validation-for="EmailId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NewPassword" class="control-label"></label>
                    <input asp-for="NewPassword" class="form-control" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }